Importing the dependencies

In [7]:
import numpy as np
import pandas as pd
import difflib#close matches   name of favourite movie by user , user give diffrent spelling name so find the similarity due to apelling incorect
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity # help to find out similarity scor

Data Collection and pre preocessing

In [8]:
#loading the csv file to pandas data frame
movies_data= pd.read_csv('/content/movies.csv')



In [24]:
# printomg the five rows of data frame
movies_data.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [25]:
movies_data.shape

(4803, 24)

In [11]:
#selecting the relevant features for recommendation
selected_features=['genres','keywords','original_language','tagline','cast','director','popularity']
print(selected_features)

['genres', 'keywords', 'original_language', 'tagline', 'cast', 'director', 'popularity']


In [12]:
#replacing the null values with null string
for features in selected_features:
  movies_data[features]=movies_data[features].fillna(' ')#filling with space value

In [59]:
#combing all the 5 selected features
combined_features=movies_data['genres']+' '+movies_data['keywords']+' '+movies_data['original_language']+' '
+movies_data['tagline']+' '+movies_data['cast']+' '+movies_data['director']+' '+str(movies_data ['popularity'])
combined_features.shape
print(combined_features)


0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
4798    Action Crime Thriller united states\u2013mexic...
4799                                 Comedy Romance   en 
4800    Comedy Drama Romance TV Movie date love at fir...
4801                                                  en 
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object


In [61]:
#convert the text data into the numerical data


vectorizer= TfidfVectorizer()
feature_vectors= vectorizer.fit_transform(combined_features) 
print(feature_vectors)
type(feature_vectors)
feature_vectors.shape



  (0, 1261)	0.0528064693869296
  (0, 3570)	0.3327387909572998
  (0, 805)	0.3814156974380689
  (0, 4236)	0.19631688634644545
  (0, 3601)	0.5326438996024705
  (0, 1546)	0.28032867257496663
  (0, 751)	0.3470159684516804
  (0, 973)	0.3268934169596726
  (0, 1427)	0.15865222242472912
  (0, 3386)	0.15846669578468012
  (0, 1386)	0.16986606319228456
  (0, 56)	0.138965282793954
  (0, 36)	0.12023723301524882
  (1, 2219)	0.2176297052292441
  (1, 2693)	0.2451945491620781
  (1, 2679)	0.16892693152593496
  (1, 2263)	0.18946722309003242
  (1, 833)	0.30543116557432043
  (1, 3975)	0.3650701437801851
  (1, 1914)	0.308544194648605
  (1, 1216)	0.2997836762809035
  (1, 1997)	0.25021316381662795
  (1, 1331)	0.30543116557432043
  (1, 25)	0.2672002176935196
  (1, 1179)	0.22262304907667638
  :	:
  (4799, 3277)	0.7603546989952262
  (4799, 817)	0.5748471097596167
  (4799, 1261)	0.30234340098122503
  (4800, 3860)	0.3413071339235796
  (4800, 3498)	0.3378635461018256
  (4800, 1451)	0.31874755009715594
  (4800, 229)	

(4803, 4380)

Cosine similarity

In [15]:
#getting the similarity score using cosine similarity
similarity=cosine_similarity(feature_vectors)
print(similarity)
print(similarity.shape)
#for each movie we will compare wih all the other movies. For eg. Batman --
#it will take Batman movie and it will try to compare with the other movies there in the data set
#it will give similarity score of each movie

[[1.         0.05947062 0.04617037 ... 0.00280448 0.05280647 0.00357783]
 [0.05947062 1.         0.04197713 ... 0.04225943 0.04801053 0.00325289]
 [0.04617037 0.04197713 1.         ... 0.00354198 0.06669319 0.00451871]
 ...
 [0.00280448 0.04225943 0.00354198 ... 1.         0.05310856 0.0035983 ]
 [0.05280647 0.04801053 0.06669319 ... 0.05310856 1.         0.06775367]
 [0.00357783 0.00325289 0.00451871 ... 0.0035983  0.06775367 1.        ]]
(4803, 4803)


Movie name from user

In [16]:
#getting the movie name from the user
movie_name=input('Enter the movie name :')

#creating the list with all the movie names given in the datset
list_of_all_titles= movies_data['title'].tolist()# it will compare movie name'Batman' with the list of movies
print(movie_name)

Enter the movie name :Race
Race


In [17]:
#finding the close match for the movie name given by the user
find_close_match=difflib.get_close_matches(movie_name,list_of_all_titles)
print(find_close_match)
close_match=find_close_match[0] #chossing the first value For eg: Batmab dark night, Batman dark night begins, Batman -----choose Batman
print(close_match)

['Race', 'Redacted', 'Rat Race']
Race


In [18]:
#finding the index of the movie with the title
index_of_the_movie=movies_data[movies_data.title==close_match]['index'].values[0] #locate the name of the movie and its corresponding index at first[0]
print(index_of_the_movie)

3584


In [19]:
#getting the list of similar movies
similarity_score=list(enumerate(similarity[index_of_the_movie])) # to run the loop in a particularly list
#if the movie is same the similarity_score is high and vice-versa
print(similarity_score)

[(0, 0.018917185603931217), (1, 0.01719910789755482), (2, 0.023891910934901825), (3, 0.0310108134505126), (4, 0.02188995676112681), (5, 0.02044165982316831), (6, 0.003973839797425554), (7, 0.019723244297762597), (8, 0.003361679280621407), (9, 0.02124881481815153), (10, 0.020804589209502802), (11, 0.021445168371699082), (12, 0.020481833412547366), (13, 0.019019668701229998), (14, 0.019220147040085518), (15, 0.0031403581693847057), (16, 0.01925033625422654), (17, 0.020766008424594314), (18, 0.016244563127050117), (19, 0.019817481279863165), (20, 0.019152624877754227), (21, 0.016603680715690777), (22, 0.0035714101630712346), (23, 0.003628572409994698), (24, 0.02363778565133161), (25, 0.012696456821004034), (26, 0.0232005959215932), (27, 0.018132764719813385), (28, 0.020763626305274778), (29, 0.021837962965184147), (30, 0.01941100554638374), (31, 0.02075411615586729), (32, 0.0030360129024082946), (33, 0.0182250516501709), (34, 0.14437526515950017), (35, 0.020870642086221643), (36, 0.019531

In [20]:
len(similarity_score)

4803

In [65]:
#sorting the movies based on thier similarity score
sorted_similarity_movies=sorted(similarity_score,key=lambda x:x[1],reverse=True)# to sort or arrange the elements of the list
#x:x[1]--particular list similarity score, reverse: want to arrange value of the similarity score for highest to lowest
print(sorted_similarity_movies)

[(3584, 1.0), (1409, 0.459297695123825), (1888, 0.4310078893664807), (1943, 0.4296078331142648), (3279, 0.4000286099390732), (3195, 0.39412804081660746), (685, 0.3816973194089385), (1295, 0.3700861694019725), (3039, 0.3570428561654701), (2297, 0.34429539952316335), (3989, 0.3399401293324531), (2829, 0.33209333878141406), (1383, 0.32424166065605114), (4536, 0.32122254120563787), (1597, 0.31235068188705245), (2242, 0.2962413817876681), (2557, 0.2962413817876681), (3527, 0.29548108579133864), (4587, 0.2930296520429119), (456, 0.2879468505231949), (2259, 0.28313844572825503), (2436, 0.28313844572825503), (2770, 0.28313844572825503), (3788, 0.2817780215111575), (1759, 0.2771090739864545), (1944, 0.2753121696332682), (2672, 0.27432371743225287), (1706, 0.27185741152905657), (235, 0.26503313805963424), (1211, 0.26427528016069535), (1979, 0.2638787731224668), (2205, 0.2635835150079542), (3447, 0.2619658527243722), (1667, 0.2588863897269647), (3756, 0.25376818816532876), (1875, 0.25115963091036

In [22]:
#print the name of similar movies based on the index
print('Movies suggested for you: \n')
i=1
for movie in sorted_similarity_movies:    
  index=movie[0]
  title_from_index=movies_data[movies_data.index==index]['title'].values[0] #from index finding the movies
  if (i<30): #run 30 times to give 30 movie
    print(i,'.',title_from_index)#movie is printed with the serial number
    i+=1

Movies suggested for you: 

1 . Race
2 . J. Edgar
3 . Eddie the Eagle
4 . Without Limits
5 . Prefontaine
6 . Princess Kaiulani
7 . Blades of Glory
8 . Against the Ropes
9 . My Week with Marilyn
10 . The Book Thief
11 . Lage Raho Munna Bhai
12 . Patton
13 . Radio
14 . The Other Dream Team
15 . Southpaw
16 . Flash of Genius
17 . The Great Debaters
18 . Chariots of Fire
19 . The Dark Hours
20 . Fury
21 . The Game of Their Lives
22 . Bobby Jones: Stroke of Genius
23 . Resurrecting the Champ
24 . Guten Tag, Ramón
25 . The Right Stuff
26 . Me and Orson Welles
27 . Cool Runnings
28 . Miracle
29 . Asterix at the Olympic Games


Movie Recommendation system

In [23]:
movie_name=input('Enter the movie name :')

#creating the list with all the movie names given in the datset
list_of_all_titles= movies_data['title'].tolist()# it will compare movie name'Batman' with the list of movies
print(movie_name)
find_close_match=difflib.get_close_matches(movie_name,list_of_all_titles)

close_match=find_close_match[0] #chossing the first value For eg: Batmab dark night, Batman dark night begins, Batman -----choose Batman
index_of_the_movie=movies_data[movies_data.title==close_match]['index'].values[0]
similarity_score=list(enumerate(similarity[index_of_the_movie])) 
sorted_similarity_movies=sorted(similarity_score,key=lambda x:x[1],reverse=True)
print('Movies suggested for you: \n')
i=1
for movie in sorted_similarity_movies:    
  index=movie[0]
  title_from_index=movies_data[movies_data.index==index]['title'].values[0] #from index finding the movies
  if (i<30): #run 30 times to give 30 movie
    print(i,'.',title_from_index)#movie is printed with the serial number
    i+=1

Enter the movie name :Race
Race
Movies suggested for you: 

1 . Race
2 . J. Edgar
3 . Eddie the Eagle
4 . Without Limits
5 . Prefontaine
6 . Princess Kaiulani
7 . Blades of Glory
8 . Against the Ropes
9 . My Week with Marilyn
10 . The Book Thief
11 . Lage Raho Munna Bhai
12 . Patton
13 . Radio
14 . The Other Dream Team
15 . Southpaw
16 . Flash of Genius
17 . The Great Debaters
18 . Chariots of Fire
19 . The Dark Hours
20 . Fury
21 . The Game of Their Lives
22 . Bobby Jones: Stroke of Genius
23 . Resurrecting the Champ
24 . Guten Tag, Ramón
25 . The Right Stuff
26 . Me and Orson Welles
27 . Cool Runnings
28 . Miracle
29 . Asterix at the Olympic Games
